// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WPFProject01;

#nullable disable

namespace WPFProject01.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20250518081350_addChildernMenu")]
    partial class addChildernMenu
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WPFProject01.Entities.Menu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MenuId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint");

                    b.Property<string>("View")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MenuId");

                    b.ToTable("Menu", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Icon = "Home",
                            Name = "主页",
                            View = "HomeView"
                        },
                        new
                        {
                            Id = 2,
                            Icon = "Settings",
                            Name = "系统设置"
                        },
                        new
                        {
                            Id = 3,
                            Icon = "AccountCircle",
                            Name = "用户管理",
                            ParentId = 2L,
                            View = "UserView"
                        },
                        new
                        {
                            Id = 4,
                            Icon = "Lock",
                            Name = "权限管理",
                            ParentId = 2L,
                            View = "PermissionView"
                        },
                        new
                        {
                            Id = 5,
                            Icon = "History",
                            Name = "日志查看",
                            View = "LogView"
                        },
                        new
                        {
                            Id = 6,
                            Icon = "Information",
                            Name = "关于",
                            View = "AboutView"
                        });
                });

            modelBuilder.Entity("WPFProject01.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsSelected")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("User", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsSelected = false,
                            Password = "admin",
                            Role = 0,
                            Telephone = "18183041275",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("WPFProject01.Entities.Menu", b =>
                {
                    b.HasOne("WPFProject01.Entities.Menu", null)
                        .WithMany("Children")
                        .HasForeignKey("MenuId");
                });

            modelBuilder.Entity("WPFProject01.Entities.Menu", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
